// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 用户基础信息
type UserBase struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	LoginName            string   `protobuf:"bytes,2,opt,name=LoginName,proto3" json:"LoginName,omitempty"`
	IDC                  string   `protobuf:"bytes,3,opt,name=IDC,proto3" json:"IDC,omitempty"`
	Nickname             string   `protobuf:"bytes,4,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
	Age                  int64    `protobuf:"varint,5,opt,name=Age,proto3" json:"Age,omitempty"`
	Male                 string   `protobuf:"bytes,6,opt,name=Male,proto3" json:"Male,omitempty"`
	Avatar               string   `protobuf:"bytes,7,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Location             string   `protobuf:"bytes,8,opt,name=Location,proto3" json:"Location,omitempty"`
	Profession           string   `protobuf:"bytes,9,opt,name=Profession,proto3" json:"Profession,omitempty"`
	Status               int64    `protobuf:"varint,10,opt,name=Status,proto3" json:"Status,omitempty"`
	CreateTime           string   `protobuf:"bytes,11,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserBase) Reset()         { *m = UserBase{} }
func (m *UserBase) String() string { return proto.CompactTextString(m) }
func (*UserBase) ProtoMessage()    {}
func (*UserBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_35595e1e1b21008e, []int{0}
}
func (m *UserBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserBase.Unmarshal(m, b)
}
func (m *UserBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserBase.Marshal(b, m, deterministic)
}
func (dst *UserBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserBase.Merge(dst, src)
}
func (m *UserBase) XXX_Size() int {
	return xxx_messageInfo_UserBase.Size(m)
}
func (m *UserBase) XXX_DiscardUnknown() {
	xxx_messageInfo_UserBase.DiscardUnknown(m)
}

var xxx_messageInfo_UserBase proto.InternalMessageInfo

func (m *UserBase) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserBase) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *UserBase) GetIDC() string {
	if m != nil {
		return m.IDC
	}
	return ""
}

func (m *UserBase) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserBase) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *UserBase) GetMale() string {
	if m != nil {
		return m.Male
	}
	return ""
}

func (m *UserBase) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserBase) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *UserBase) GetProfession() string {
	if m != nil {
		return m.Profession
	}
	return ""
}

func (m *UserBase) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UserBase) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

type UserContact struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=Phone,proto3" json:"Phone,omitempty"`
	WeChatId             string   `protobuf:"bytes,4,opt,name=WeChatId,proto3" json:"WeChatId,omitempty"`
	WeiBoId              string   `protobuf:"bytes,5,opt,name=WeiBoId,proto3" json:"WeiBoId,omitempty"`
	QQId                 string   `protobuf:"bytes,6,opt,name=QQId,proto3" json:"QQId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserContact) Reset()         { *m = UserContact{} }
func (m *UserContact) String() string { return proto.CompactTextString(m) }
func (*UserContact) ProtoMessage()    {}
func (*UserContact) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_35595e1e1b21008e, []int{1}
}
func (m *UserContact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserContact.Unmarshal(m, b)
}
func (m *UserContact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserContact.Marshal(b, m, deterministic)
}
func (dst *UserContact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserContact.Merge(dst, src)
}
func (m *UserContact) XXX_Size() int {
	return xxx_messageInfo_UserContact.Size(m)
}
func (m *UserContact) XXX_DiscardUnknown() {
	xxx_messageInfo_UserContact.DiscardUnknown(m)
}

var xxx_messageInfo_UserContact proto.InternalMessageInfo

func (m *UserContact) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserContact) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserContact) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserContact) GetWeChatId() string {
	if m != nil {
		return m.WeChatId
	}
	return ""
}

func (m *UserContact) GetWeiBoId() string {
	if m != nil {
		return m.WeiBoId
	}
	return ""
}

func (m *UserContact) GetQQId() string {
	if m != nil {
		return m.QQId
	}
	return ""
}

// 用户信息
type UserInfo struct {
	Base                 *UserBase    `protobuf:"bytes,1,opt,name=Base,proto3" json:"Base,omitempty"`
	Contact              *UserContact `protobuf:"bytes,2,opt,name=Contact,proto3" json:"Contact,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_35595e1e1b21008e, []int{2}
}
func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (dst *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(dst, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetBase() *UserBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *UserInfo) GetContact() *UserContact {
	if m != nil {
		return m.Contact
	}
	return nil
}

// id查询用户信息
type UserId struct {
	UID                  int64    `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserId) Reset()         { *m = UserId{} }
func (m *UserId) String() string { return proto.CompactTextString(m) }
func (*UserId) ProtoMessage()    {}
func (*UserId) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_35595e1e1b21008e, []int{3}
}
func (m *UserId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserId.Unmarshal(m, b)
}
func (m *UserId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserId.Marshal(b, m, deterministic)
}
func (dst *UserId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserId.Merge(dst, src)
}
func (m *UserId) XXX_Size() int {
	return xxx_messageInfo_UserId.Size(m)
}
func (m *UserId) XXX_DiscardUnknown() {
	xxx_messageInfo_UserId.DiscardUnknown(m)
}

var xxx_messageInfo_UserId proto.InternalMessageInfo

func (m *UserId) GetUID() int64 {
	if m != nil {
		return m.UID
	}
	return 0
}

func init() {
	proto.RegisterType((*UserBase)(nil), "account.UserBase")
	proto.RegisterType((*UserContact)(nil), "account.UserContact")
	proto.RegisterType((*UserInfo)(nil), "account.UserInfo")
	proto.RegisterType((*UserId)(nil), "account.UserId")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_account_35595e1e1b21008e) }

var fileDescriptor_account_35595e1e1b21008e = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xd1, 0xaa, 0xda, 0x40,
	0x10, 0x25, 0xd1, 0x9b, 0x98, 0x09, 0xbd, 0x6d, 0x97, 0x4b, 0x59, 0xa4, 0x94, 0x4b, 0xa0, 0xe0,
	0x93, 0x50, 0xfb, 0xd0, 0x67, 0x8d, 0xa5, 0x2c, 0x58, 0xd1, 0x58, 0xeb, 0xf3, 0x36, 0x59, 0x35,
	0x54, 0xb3, 0x25, 0x59, 0xfb, 0x23, 0x7d, 0xe9, 0x37, 0xf4, 0x2b, 0xcb, 0x4c, 0x76, 0xb5, 0x62,
	0xe1, 0xbe, 0xcd, 0x39, 0x73, 0xce, 0x64, 0xf6, 0x4c, 0xe0, 0x99, 0xcc, 0x73, 0x7d, 0xaa, 0xcc,
	0xf0, 0x47, 0xad, 0x8d, 0x66, 0xa1, 0x85, 0xc9, 0x6f, 0x1f, 0x7a, 0xeb, 0x46, 0xd5, 0x13, 0xd9,
	0x28, 0x76, 0x0f, 0xbe, 0x28, 0xb8, 0xf7, 0xe8, 0x0d, 0x3a, 0x99, 0x2f, 0x0a, 0xf6, 0x1a, 0xa2,
	0x99, 0xde, 0x95, 0xd5, 0x5c, 0x1e, 0x15, 0xf7, 0x1f, 0xbd, 0x41, 0x94, 0x5d, 0x08, 0xf6, 0x02,
	0x3a, 0x62, 0x9a, 0xf2, 0x0e, 0xf1, 0x58, 0xb2, 0x3e, 0xf4, 0xe6, 0x65, 0xfe, 0xbd, 0x42, 0x79,
	0x97, 0xe8, 0x33, 0x46, 0xf5, 0x78, 0xa7, 0xf8, 0x1d, 0x0d, 0xc7, 0x92, 0x31, 0xe8, 0x7e, 0x96,
	0x07, 0xc5, 0x03, 0x52, 0x52, 0xcd, 0x5e, 0x41, 0x30, 0xfe, 0x29, 0x8d, 0xac, 0x79, 0x48, 0xac,
	0x45, 0x38, 0x79, 0xa6, 0x73, 0x69, 0x4a, 0x5d, 0xf1, 0x5e, 0x3b, 0xd9, 0x61, 0xf6, 0x06, 0x60,
	0x51, 0xeb, 0xad, 0x6a, 0x1a, 0xec, 0x46, 0xd4, 0xfd, 0x87, 0xc1, 0x99, 0x2b, 0x23, 0xcd, 0xa9,
	0xe1, 0x40, 0x1f, 0xb7, 0x08, 0x7d, 0x69, 0xad, 0xa4, 0x51, 0x5f, 0xca, 0xa3, 0xe2, 0x71, 0xeb,
	0xbb, 0x30, 0xc9, 0x2f, 0x0f, 0x62, 0x8c, 0x26, 0xd5, 0x95, 0x91, 0xb9, 0xb9, 0x49, 0xe7, 0x01,
	0xee, 0x3e, 0x1e, 0x65, 0x79, 0xb0, 0xc9, 0xb4, 0x00, 0xd9, 0xc5, 0x5e, 0x57, 0xca, 0xe6, 0xd2,
	0x02, 0xdc, 0x7f, 0xa3, 0xd2, 0xbd, 0x34, 0xa2, 0x70, 0xc9, 0x38, 0xcc, 0x38, 0x84, 0x1b, 0x55,
	0x4e, 0xb4, 0x28, 0x28, 0x9d, 0x28, 0x73, 0x10, 0x13, 0x5a, 0x2e, 0x45, 0xe1, 0x12, 0xc2, 0x3a,
	0x91, 0xed, 0xbd, 0x44, 0xb5, 0xd5, 0xec, 0x2d, 0x74, 0xf1, 0x6e, 0xb4, 0x53, 0x3c, 0x7a, 0x39,
	0x74, 0x37, 0x76, 0x07, 0xcd, 0xa8, 0xcd, 0x86, 0x10, 0xda, 0x37, 0xd0, 0xaa, 0xf1, 0xe8, 0xe1,
	0x4a, 0x69, 0x7b, 0x99, 0x13, 0x25, 0x7d, 0x08, 0xe8, 0x13, 0x05, 0x1e, 0x6d, 0x2d, 0xa6, 0xf6,
	0xcd, 0x58, 0x8e, 0xfe, 0x78, 0x10, 0x8d, 0x5b, 0xf3, 0xea, 0x2b, 0x7b, 0x07, 0xf1, 0x27, 0x65,
	0xce, 0xfb, 0x3c, 0xbf, 0x9a, 0x2b, 0x8a, 0xfe, 0xf5, 0x4a, 0xa4, 0xb9, 0x58, 0x68, 0xb7, 0x27,
	0x2c, 0xa4, 0xf9, 0x00, 0xf7, 0xd6, 0xe2, 0x4e, 0x71, 0xe3, 0xfa, 0xef, 0x8b, 0xbe, 0x05, 0xf4,
	0xb3, 0xbf, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x8e, 0x24, 0x2f, 0x88, 0xfd, 0x02, 0x00, 0x00,
}
